[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  