[build]
  publish = "dist"
  command = "npm install --force && npm run build"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.8"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  